site_name: Rostyslav Fedechko | Digital Marketing
site_description: Portfolio of Performance Marketing Specialist
site_author: Rostyslav Fedechko

theme:
  name: material
  palette:
    # Світла тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Перемкнути на темну тему
    # Темна тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Перемкнути на світлу тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate

nav:
  - Про мене: index.md
  - Досвід роботи: experience.md
  - Навички та Освіта: skills.md